version: '3.9'

services:
  db:
    image: postgres
    container_name: db
    ports:
      - 5434:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=speciial
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    user: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  spring:
    build: .
    container_name: spring
    ports:
      - 8083:8083
    extra_hosts:
      - "auth-server:127.0.0.1"
      - "client-server:127.0.0.1"
      - "resources-server:127.0.0.1"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - frontend
      - backend

volumes:
  postgres_data:
    driver: local

networks:
  frontend:
    external: true
  backend:
    internal: true